name: bazi_core
description: "Dart/Flutter 八字（BaZi）计算库，支持真太阳时、早晚子时配置、农历/阳历转换等功能。"
version: 0.1.0
homepage: https://github.com/RedSC1/bazi_core

environment:
  sdk: ^3.10.8

dependencies:
  sxwnl_spa_dart: ^0.9.6
dev_dependencies:
  test: ^1.29.0
  lints: ^6.1.0

